### ISSUE TITLE
Lingering issue

### ISSUE THREAD

**Issue by AltoRetrato** [jason-richards/featherweb#3]
Hey, Jason!

I'm not sure if this is a featherweb or MicroPython issue.

I wrote a script to read data from a sensor at about every 30 s. I run featherweb with a 3 s timeout and in the callback function I check if 30 s or more have passed since the last reading.

It works fine most of the time, but after any http request the server seems to linger for a random amount of time, e.g., 0 s, 45 s, 38 s, 9 s, ...

I unfolded this code:
```
response = HTTPRequest(client, f.readline())
```
into:
```
line = f.readline()
response = HTTPRequest(client, line)
```
The server lingers during `line = f.readline()`.

Any idea of the cause?

**Comment by AltoRetrato** [comment]
Also, this issue seems to always happen after calling sendfile(). And when this happens, the line read is always `b''`. So this is related to #2 .

**Comment by jason-richards** [comment]
SO_LINGER?  Let me know if you have a solid way to reproduce

**Comment by AltoRetrato** [comment]
I'm not sure if this helps at all, but here is an annotated sample log file from my script and modified featherweb:
```
[2020/06/13 14:06:43] 2020/06/13 14:06:43, IP(s): ('192.168.1.106', '192.168.4.1')
[2020/06/13 14:06:43] Starting webserver...
[2020/06/13 14:06:46] Sampling data
[2020/06/13 14:06:46] Saving data

(Requested http://192.168.1.106/now, served with request.send(), no issues)
[2020/06/13 14:06:46] About to read socket...
[2020/06/13 14:06:46] Line read in 11 ms: b'GET /now HTTP/1.1\r\n'
[2020/06/13 14:06:47] About to read socket...
[2020/06/13 14:06:47] Line read in 17 ms: b'GET /favicon.png HTTP/1.1\r\n'

(Requested http://192.168.1.106/now, served with request.send(), no issues)
[2020/06/13 14:06:54] About to read socket...
[2020/06/13 14:06:54] Line read in 11 ms: b'GET /now HTTP/1.1\r\n'
[2020/06/13 14:06:55] About to read socket...
[2020/06/13 14:06:55] Line read in 16 ms: b'GET /favicon.png HTTP/1.1\r\n'

(Requested http://192.168.1.106/download, served with request.sendfile(), 
data is promptly received but server lingers afterwards - notice 17 sec. delay)
[2020/06/13 14:06:59] About to read socket...
[2020/06/13 14:07:00] Line read in 14 ms: b'GET /download HTTP/1.1\r\n'
[2020/06/13 14:07:00] About to read socket...
[2020/06/13 14:07:17] Line read in 16581 ms: b''
[2020/06/13 14:07:20] Sampling data
[2020/06/13 14:07:20] Saving data

(Requested http://192.168.1.106/log, served with request.sendfile(), 
data is promptly received but server lingers afterwards - notice 27 sec. delay)
[2020/06/13 14:07:26] About to read socket...
[2020/06/13 14:07:26] Line read in 11 ms: b'GET /log HTTP/1.1\r\n'
[2020/06/13 14:07:27] About to read socket...
[2020/06/13 14:07:54] Line read in 27019 ms: b''
[2020/06/13 14:07:57] Sampling data
[2020/06/13 14:07:57] Saving data
[2020/06/13 14:08:03] Clean shutdown.
```

To make it a bit easier to understand, this is the code section with the issue:
```
                        log("About to read socket...")
                        before = time.ticks_ms()
                        line = f.readline()
                        ms     = time.ticks_ms() - before
                        log("Line read in {} ms: {}".format(ms, repr(line)))
                        if not line or line == b'\r\n':
                            break
                        response = HTTPRequest(client, line)
                        # The code above replaces the original line below:
                        # response = HTTPRequest(client, f.readline())
```
BTW, the server will immediately stop lingering when receiving a new request, but will linger again once more. But after `line = f.readline()` reads `b''`, it will stop lingering (until the next time request.sendfile() is called).

**Comment by AltoRetrato** [comment]
Now, this is interesting...

I can ALWAYS reproduce the issue with Google Chrome on Windows, but I can NEVER reproduce it with cURL!

Even if I "copy as cURL" the command from the Chrome DevTools window, I can't trigger the issue.

Sample code:
```
import featherweb
import wifi

app = featherweb.FeatherWeb()

@app.route('/send')
def serve_with_send(request):
    msg = "Served with request.send()"
    request.send(msg)
    print(msg)

if __name__ == "__main__":
    wifi.connect()
    print("Starting webserver...")
    app.run(timeout=3)
```

I captured packets to and from the ESP32 with Wireshark:

- ESP32 has IP 192.168.1.106, my PC has 192.168.1.103
- cURL connection starts at packet 13 (3.6821 s) and ends at packets 26 & 27 (4.015 s)
- Google Chrome connection starts at packet 29 (8.7866 s) and should end at packets 42 & 43 (9.209 s), but it lingers until packet 47 (20.2798 s)

[wireshark.zip](https://github.com/jason-richards/featherweb/files/4775413/wireshark.zip)

FWIW, I tried the same with Firefox, and like with cURL it also worked flawlessly (no lingering at all).

I'm not sure if any of this information is helpful, but I hope you might be able to see something I'm not. If you have any ideas, I'm willing to do some more tests.

**Comment by jason-richards** [comment]
Cool - Based on your description above I think it has to do with Chrome speculative connection.  I set the timeout on the client socket returned by accept.  That will fix the problem.  I need to figure out how to handle the exception in micropython... but your 17 sec delay should be cut to the timeout you set when you create the server.  Do a pull and let me knwo..

**Comment by AltoRetrato** [comment]
"[Chrome Preconnect Breaks Singly Threaded Servers](https://hackernoon.com/chrome-preconnect-breaks-singly-threaded-servers-95944be16400)", it seems.

The timeout on the client ends up producing a 404 on the next Chrome request. :(

I was planning to move my code to an async server on a later date, but it seems I'll have to do it sooner than expected...

Thanks so much for your kind and prompt attention, Jason!

**Comment by jason-richards** [comment]
Sure.  The exception handling should be changed so it doesn't return a 404
on timeout.  Just need to check uerrno.

I wrote this for esp8266.  Asychio library requires too much memory and
crashes esp.  biggest problem is memory fragmentation.  Second biggest is
the more requests you have waiting the more memory is required... Which
crash esp

**Comment by jason-richards** [comment]
Updated server to timeout speculative connections from Chrome.  Now closes connection on timeout without sending response

**Comment by AltoRetrato** [comment]
Looking good! 👍  No issues after a quick test.

**Comment by AltoRetrato** [comment]
Looking good! 👍  

No more 404 errors or other issues with Chrome!

But unfortunately, when I close the server with Ctrl+C and restart it, it once again shows `OSError: [Errno 98] EADDRINUSE`...

**Comment by jason-richards** [comment]
Eww... probably have to close those pesky file descriptors we created.
